version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=pratishthaabrol
      - POSTGRES_PASSWORD=1234test
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '8080:5432'
volumes:
  postgres:
